### PR TITLE
Add support for `go_custom_stringer`.

### PR DESCRIPTION
**Pull request by connyay**
This change enables a new enum option:
```
option (go_custom_stringer) = true;
```

With this specified the out of the box String() impl is renamed to
_String() which allows adding custom stringer implementations.

### CODE REVIEW

**Comment by connyay** [comment]
Replaces the need for 
```
option (gogoproto.enum_stringer) = false;
```

opened as a draft as wasn't sure if this is something y'all need/care about.

**Comment by ydnar** [comment]
Thanks! This seems useful.

It’s unfortunate that you can’t have multiple extensions with the same name in a single proto (or Go package). See `go_enum_name` vs just using `go_name` everywhere. In that vein, I’d probably rename this to `go_enum_stringer` and invert it, so `false` renames the old `String` method.

Google [recommends extensions use a defined message](https://developers.google.com/protocol-buffers/docs/proto#options), instead of individual `string` or `bool` options. In theory this could look something like this:

```proto
import "patch/go/enum.proto";

enum PaintColor {
    option (go.enum.options) = {name: 'Color'};
}
```

**Comment by connyay** [comment]
`GetExtension` returns default val if unpopulated :-/ 

Will poke at a custom message for it.

**Comment by ydnar** [comment]
I was thinking something like this:

```proto
syntax = "proto2";

// clang-format off
package go.enum;
// clang-format on

import "google/protobuf/descriptor.proto";

option go_package = "github.com/alta/protopatch/patch/go/enum";

message Options {
	// name, if specified, renames the generated Go type for this enum.
	optional string name = 1;

	// stringer_name, if specified, renames the generated String() method
	// so a custom String() method can be implemented for the generated type.
	optional bool stringer_name = 10;
}

extend google.protobuf.EnumOptions {
	optional Options options = 7001;
}
```

**Comment by ydnar** [comment]
Have something working in #3.

**Comment by connyay** [comment]
#3 is way better

**Pull request closed without merging**
